---
bootstrap.servers: "10.54.17.74:9092"
sasl.mechanisms: "PLAIN"
security.protocol: "SASL_SSL"
sasl.username: "user"
sasl.password: "secret1"
ssl.ca.location: ""
group.id: "test"
topics: "gnf.network.telemetry"
#auto.offset.reset: "earliest"
auto.offset.reset: "latest"